name: test

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - 'src/**.rs'

env:
  CI: true
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.84.0
        components: clippy, rustfmt
    - name: Install tarpaulin
      run: cargo install --locked cargo-tarpaulin
    - name: Run build
      run: cargo build --locked
    - name: Run clippy
      run: cargo clippy --locked --all-targets --all-features --no-deps -- -D warnings
    - name: Run lint
      run: cargo fmt -- --check
    - name: Run tests
      run: cargo tarpaulin --locked --out xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: ./cobertura.xml
